name: quizmaster
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.2
  json_annotation: ^4.5.0
  rxdart: ^0.27.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  firebase_storage: ^10.2.17
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.1
  # font_awesome_flutter: 9.2.0
  # google_fonts: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/default.png