// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxaCO8nyWshI69dNKzRr1O-ec6ypMZqq0',
    appId: '1:463575168711:android:c0a72c6007dc59eaaf70e2',
    messagingSenderId: '463575168711',
    projectId: 'quizmaster-6a62a',
    databaseURL: 'https://quizmaster-6a62a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizmaster-6a62a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArK9_CEOcV8xkaKj-MMEsCn_DCBLOEUY8',
    appId: '1:463575168711:ios:15edb9a0d6b09ef3af70e2',
    messagingSenderId: '463575168711',
    projectId: 'quizmaster-6a62a',
    databaseURL: 'https://quizmaster-6a62a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizmaster-6a62a.appspot.com',
    iosClientId: '463575168711-vr630rtu6207impfu7nsjgj5ffs1hsq9.apps.googleusercontent.com',
    iosBundleId: 'com.kristley.quizmaster',
  );
}
